anchor/oauth2-server

- oauth2-server-demo/oauth2-server-demo.cabal
- oauth2-server-demo/src/Main.hs
- oauth2-server-snap/lib/Network/OAuth2/Server/Snap.hs
- oauth2-server-snap/oauth2-server-snap.cabal
- oauth2-server/lib/Network/OAuth2/Server/Configuration.hs
- oauth2-server/lib/Network/OAuth2/Server/Types.hs
Start calling (improperly) the logic implementation functions in the
Snap adaptor; update the demo implementation to print a message on
each password check.
> Start using the implementation functions

- tests/acceptance-tests.sh
- tests/acceptance-tests/resource-owner-password-credentials-grant.sh
> Acceptance tests should fail when they fail

- oauth2-server-demo/src/Main.hs
- oauth2-server-snap/lib/Network/OAuth2/Server/Snap.hs
- oauth2-server/lib/Network/OAuth2/Server/Types.hs
**WIP**
Add a data type to represent OAuth2 errors and a Snap handler to return them correctly to the client.
> Report errors to clients correctly

- oauth2-server-demo/src/Main.hs
- oauth2-server-snap/lib/Network/OAuth2/Server/Snap.hs
- oauth2-server/lib/Network/OAuth2/Server.hs
- oauth2-server/lib/Network/OAuth2/Server/Configuration.hs
- oauth2-server/lib/Network/OAuth2/Server/Types.hs
- oauth2-server/oauth2-server.cabal
- tests/acceptance-tests.sh
- tests/acceptance-tests/refresh-token.sh
- tests/acceptance-tests/resource-owner-password-credentials-grant.sh
Implement basic support for refresh_token grant_type.
> Refresh token request

- lib/Network/OAuth2/Server/Types.hs
- oauth2-server.cabal
- test/test.hs
Don't use the crappy URI type.
> uri-bytestring

- lib/Network/OAuth2/Server/Types.hs
> Token server helpers

- examples/postgresql-data.sql
- lib/Anchor/Tokens/Server/Store.hs
- oauth2-server.cabal
- runit.sh
- schema/postgresql.sql
- test/acceptance.hs
Start adding acceptance testing data and code and resolve the first few bugs.
> Server testing

- oauth2-server.cabal
- test/acceptance.hs
Fleshing out acceptance tests starting with the verify endpoint.
> test: acceptance tests talking to verify endpoint

- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/Types.hs
Move authorization request type into the types module, where it belongs.
> Move authorization request type into types

- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/Types.hs
- lib/Network/OAuth2/Server/UI.hs
Use UUIDs for TokenIDs instead of Text
Consolidate manual revoke
> Cleanup TokenIDs and manual revocation

- lib/Network/OAuth2/Server/API.hs
> restore vogue + required ghc exts

- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/Store.hs
- lib/Network/OAuth2/Server/Types.hs
- schema/postgresql.sql
- test/acceptance.hs
Start testing authorization endpoint, fixing a few bugs as I go.
> Authorize endpoint: start on validation, error codes, etc.

- lib/Network/OAuth2/Server/Types.hs
- lib/Network/OAuth2/Server/UI.hs
- oauth2-server.cabal
- test/acceptance.hs
There are legitimate failure now!
> Make acceptance tests more acceptable

- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/UI.hs
- test/acceptance.hs
This leaves the acceptance test breaking on NOOOOO
> Add required bits to the UI for token confirmation page

- lib/Network/OAuth2/Server/Types.hs
- lib/Network/OAuth2/Server/Types/Token.hs
- oauth2-server.cabal
Cleaned up encoding/decoding for TokenType for JSON and PostgreSQL instances + more informative errors for parsing failures
> Refactored out Token, TokenID and TokenType into separate file

- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/Configuration.hs
- lib/Network/OAuth2/Server/Store/Base.hs
- lib/Network/OAuth2/Server/Store/PostgreSQL.hs
- lib/Network/OAuth2/Server/Types.hs
- lib/Network/OAuth2/Server/Types/Auth.hs
- lib/Network/OAuth2/Server/UI.hs
- test/acceptance.hs
- test/test.hs
- test/tokenstore.hs
Consolidated functions in Store, is now more restricted CRUD, handlers now deal with logic.
Newtype wrapped PageSize, too many loose Ints were floating around.
Removed Password Grants
Expiry is now optional to facilitate manual tokens, as they have no expiry.
We may want to add the option of expiry later.
Removed Username
Updated UI to use TokenDetails instead of a specialised tuple.
> Cleaned up store, removed Password Grants

- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/Store/Base.hs
- lib/Network/OAuth2/Server/Store/PostgreSQL.hs
- test/tokenstore.hs
Brokenness is fixed with the merge.
> Some more properties for the tokenstore, uncovering brokenness

- examples/postgresql-data.sql
- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/Store/Base.hs
- lib/Network/OAuth2/Server/Store/PostgreSQL.hs
- lib/Network/OAuth2/Server/Types.hs
- runit.sh
- schema/postgresql.sql
- test/acceptance.hs
- test/tokenstore.hs
- Request codes keep track of the associated user_id associated
- Tokens have an associated parent token_id
- Revoking a token revokes any "children" it has too
- Refactor for these changes and others
- Run non-destructive acceptance-tests first
> Refreshing a token should revoke old tokens

- runit.sh
- src/tokenserver.hs
The standard is `NoBuffering`, which makes the output quite slow.
> Use Linebuffering for output

- docs/installation.md
- examples/shibboleth-apache.conf
- examples/shibboleth-attributes.xml
Please to be review and comment.
> Add an installation file

- lib/Network/OAuth2/Server/API.hs
Split the caching-related 'Header's and type-list into type aliases,
then use them. For some reason hlint has no trouble parsing them like
this.
Also: make all of the places we do caching headers do the *same*
caching headers.
> Reorganize API types so hlint can parse them

- lib/Network/OAuth2/Server.hs
- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/Types.hs
- lib/Network/OAuth2/Server/Types/Error.hs
- test/acceptance.hs
- test/tokenserver.hs
- test/tokenstore.hs
This makes all the changes so that `git-vogue check -A` says OK.
> Make changes to satisfy git-vogue

- lib/Network/OAuth2/Server/API.hs
Completed a TODO and made code surrounding it more concise.
Fixed a few minor typos/grammar/layout things.
> Cleanup little bits of code, consolidate others.

- lib/Network/OAuth2/Server.hs
- lib/Network/OAuth2/Server/API.hs
- lib/Network/Wai/Middleware/Shibboleth.hs
- test/acceptance.hs
- test/test.hs
- test/tokenstore.hs
Let's do some more cleaning up, documenting, etc.
> More haddock

- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/Types.hs
code prism did not reject empty codes
added RFC references to said code prism
cleaned up control flow in processTokenRequest in API.hs
cleaned up general code structure in API
> fixed code prism + cleaned up API.hs

- examples/test-nginx-proxy.conf
- oauth2-server.cabal
- proxy.sh
- test/use-cases.hs
Happybarra is a misnomer, no happybaras are involved.
> Add some selenium tests, much is pending.

- lib/Network/OAuth2/Server/UI.hs
- runit.sh
- style.css
Token list page it slightly better
> Slight improvements to UI

- lib/Network/OAuth2/Server.hs
- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/App.hs
- lib/Network/OAuth2/Server/Configuration.hs
- lib/Network/OAuth2/Server/Statistics.hs
- lib/Network/OAuth2/Server/Store.hs
- lib/Network/OAuth2/Server/Store/Base.hs
- lib/Network/OAuth2/Server/Store/PostgreSQL.hs
- lib/Network/OAuth2/Server/Types.hs
- lib/Network/OAuth2/Server/Types/Auth.hs
- lib/Network/OAuth2/Server/Types/Client.hs
- lib/Network/OAuth2/Server/Types/Common.hs
- lib/Network/OAuth2/Server/Types/Error.hs
- lib/Network/OAuth2/Server/Types/Scope.hs
- lib/Network/OAuth2/Server/Types/Token.hs
- lib/Network/OAuth2/Server/UI.hs
Haddock coverage:
100% ( 17 / 17) in 'Network.OAuth2.Server.Types.Common'
  50% ( 10 / 20) in 'Network.OAuth2.Server.Types.Error'
100% ( 11 / 11) in 'Network.OAuth2.Server.Types.Scope'
100% (  7 /  7) in 'Network.OAuth2.Server.Types.Token'
100% ( 15 / 15) in 'Network.OAuth2.Server.Types.Auth'
100% (  6 /  6) in 'Network.OAuth2.Server.Types.Client'
100% (  7 /  7) in 'Network.Wai.Middleware.Shibboleth'
  83% ( 55 / 66) in 'Network.OAuth2.Server.Types'
100% (  4 /  4) in 'Network.OAuth2.Server.UI'
100% (  5 /  5) in 'Network.OAuth2.Server.Store.Base'
100% (  2 /  2) in 'Network.OAuth2.Server.Store.PostgreSQL'
100% (  3 /  3) in 'Network.OAuth2.Server.Store'
100% ( 27 / 27) in 'Network.OAuth2.Server.API'
100% (  8 /  8) in 'Network.OAuth2.Server.Statistics'
100% (  3 /  3) in …
> Haddocked all of the things (apart from TH stuff) + fixed minor exposure bugs

- lib/Network/OAuth2/Server/Store/PostgreSQL.hs
- lib/Network/OAuth2/Server/UI.hs
- oauth2-server.cabal
> UI: Improve token list

- examples/token-server.conf
- lib/Network/OAuth2/Server/API.hs
- lib/Network/OAuth2/Server/Configuration.hs
- lib/Network/OAuth2/Server/Types.hs
> Configure shib headers

- static/stylesheet.css
> CSS: align pagination button
